// Code generated by protoc-gen-go-drpc. DO NOT EDIT.
// protoc-gen-go-drpc version: v0.0.32
// source: cache.proto

package pb

import (
	context "context"
	errors "errors"
	protojson "google.golang.org/protobuf/encoding/protojson"
	proto "google.golang.org/protobuf/proto"
	drpc "storj.io/drpc"
	drpcerr "storj.io/drpc/drpcerr"
)

type drpcEncoding_File_cache_proto struct{}

func (drpcEncoding_File_cache_proto) Marshal(msg drpc.Message) ([]byte, error) {
	return proto.Marshal(msg.(proto.Message))
}

func (drpcEncoding_File_cache_proto) MarshalAppend(buf []byte, msg drpc.Message) ([]byte, error) {
	return proto.MarshalOptions{}.MarshalAppend(buf, msg.(proto.Message))
}

func (drpcEncoding_File_cache_proto) Unmarshal(buf []byte, msg drpc.Message) error {
	return proto.Unmarshal(buf, msg.(proto.Message))
}

func (drpcEncoding_File_cache_proto) JSONMarshal(msg drpc.Message) ([]byte, error) {
	return protojson.Marshal(msg.(proto.Message))
}

func (drpcEncoding_File_cache_proto) JSONUnmarshal(buf []byte, msg drpc.Message) error {
	return protojson.Unmarshal(buf, msg.(proto.Message))
}

type DRPCCacheServiceClient interface {
	DRPCConn() drpc.Conn

	Get(ctx context.Context, in *Key) (*Value, error)
	Put(ctx context.Context, in *Entry) (*Nil, error)
	Delete(ctx context.Context, in *Key) (*Nil, error)
}

type drpcCacheServiceClient struct {
	cc drpc.Conn
}

func NewDRPCCacheServiceClient(cc drpc.Conn) DRPCCacheServiceClient {
	return &drpcCacheServiceClient{cc}
}

func (c *drpcCacheServiceClient) DRPCConn() drpc.Conn { return c.cc }

func (c *drpcCacheServiceClient) Get(ctx context.Context, in *Key) (*Value, error) {
	out := new(Value)
	err := c.cc.Invoke(ctx, "/pb.CacheService/Get", drpcEncoding_File_cache_proto{}, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drpcCacheServiceClient) Put(ctx context.Context, in *Entry) (*Nil, error) {
	out := new(Nil)
	err := c.cc.Invoke(ctx, "/pb.CacheService/Put", drpcEncoding_File_cache_proto{}, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drpcCacheServiceClient) Delete(ctx context.Context, in *Key) (*Nil, error) {
	out := new(Nil)
	err := c.cc.Invoke(ctx, "/pb.CacheService/Delete", drpcEncoding_File_cache_proto{}, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type DRPCCacheServiceServer interface {
	Get(context.Context, *Key) (*Value, error)
	Put(context.Context, *Entry) (*Nil, error)
	Delete(context.Context, *Key) (*Nil, error)
}

type DRPCCacheServiceUnimplementedServer struct{}

func (s *DRPCCacheServiceUnimplementedServer) Get(context.Context, *Key) (*Value, error) {
	return nil, drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

func (s *DRPCCacheServiceUnimplementedServer) Put(context.Context, *Entry) (*Nil, error) {
	return nil, drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

func (s *DRPCCacheServiceUnimplementedServer) Delete(context.Context, *Key) (*Nil, error) {
	return nil, drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

type DRPCCacheServiceDescription struct{}

func (DRPCCacheServiceDescription) NumMethods() int { return 3 }

func (DRPCCacheServiceDescription) Method(n int) (string, drpc.Encoding, drpc.Receiver, interface{}, bool) {
	switch n {
	case 0:
		return "/pb.CacheService/Get", drpcEncoding_File_cache_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCCacheServiceServer).
					Get(
						ctx,
						in1.(*Key),
					)
			}, DRPCCacheServiceServer.Get, true
	case 1:
		return "/pb.CacheService/Put", drpcEncoding_File_cache_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCCacheServiceServer).
					Put(
						ctx,
						in1.(*Entry),
					)
			}, DRPCCacheServiceServer.Put, true
	case 2:
		return "/pb.CacheService/Delete", drpcEncoding_File_cache_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCCacheServiceServer).
					Delete(
						ctx,
						in1.(*Key),
					)
			}, DRPCCacheServiceServer.Delete, true
	default:
		return "", nil, nil, nil, false
	}
}

func DRPCRegisterCacheService(mux drpc.Mux, impl DRPCCacheServiceServer) error {
	return mux.Register(impl, DRPCCacheServiceDescription{})
}

type DRPCCacheService_GetStream interface {
	drpc.Stream
	SendAndClose(*Value) error
}

type drpcCacheService_GetStream struct {
	drpc.Stream
}

func (x *drpcCacheService_GetStream) SendAndClose(m *Value) error {
	if err := x.MsgSend(m, drpcEncoding_File_cache_proto{}); err != nil {
		return err
	}
	return x.CloseSend()
}

type DRPCCacheService_PutStream interface {
	drpc.Stream
	SendAndClose(*Nil) error
}

type drpcCacheService_PutStream struct {
	drpc.Stream
}

func (x *drpcCacheService_PutStream) SendAndClose(m *Nil) error {
	if err := x.MsgSend(m, drpcEncoding_File_cache_proto{}); err != nil {
		return err
	}
	return x.CloseSend()
}

type DRPCCacheService_DeleteStream interface {
	drpc.Stream
	SendAndClose(*Nil) error
}

type drpcCacheService_DeleteStream struct {
	drpc.Stream
}

func (x *drpcCacheService_DeleteStream) SendAndClose(m *Nil) error {
	if err := x.MsgSend(m, drpcEncoding_File_cache_proto{}); err != nil {
		return err
	}
	return x.CloseSend()
}
